### ISSUE TITLE
I can not find 'getTags()' in version 1.0.2

### ISSUE THREAD

**Issue by arkanmgerges** [whilu/AndroidTagView#11]
Hi, I used your lib in my project, but I could not find getTags() in your code.

Thanks

**Comment by whilu** [comment]
@arkanmgerges Thanks! ```getTags()``` method is not located in ```v1.0.2```, it will be provided in ```v1.0.3``` soon. If you want to use it now, just import the library locally or use with [https://jitpack.io/#whilu/AndroidTagView/-SNAPSHOT](https://jitpack.io/#whilu/AndroidTagView/-SNAPSHOT)

**Comment by arkanmgerges** [comment]
Hi,
I used https://jitpack.io, and it solved the problem without downloading the project locally. I only referred to the git repo directly by respecting how the url must be provided, and it solved the problem.
Thanks
