### ISSUE TITLE
Not able to change the tagTextColor or tagBackgroundColor

### ISSUE THREAD

**Issue by ndeokar** [whilu/AndroidTagView#13]
All the provided methods are not working for changing the tag text color. 

i tried using 

```

 mTagContainerLayout.setTagBorderColor(Color.WHITE);

 mTagContainerLayout.setTagTextColor(Color.WHITE);

mTagContainerLayout.setTagBackgroundColor(Color.TRANSPARENT);
```

even i tried changing the default values.

   ```
 /** TagView border color(default #88F44336)*/
    private int mTagBorderColor = Color.WHITE;

    /** TagView background color(default #33F44336)*/
    private int mTagBackgroundColor =  Color.TRANSPARENT;

    /** TagView text color(default #FF666666)*/
    private int mTagTextColor =  Color.WHITE;
```

i am still getting the default background color for every tag.

Thanks!

**Comment by ravirupareliya** [comment]
yes, in my case also setting it runtime is not working, but if you will set it from xml file it will work perfectly. Like this

    app:container_background_color="#ff0000"

**Comment by ndeokar** [comment]
@ravirupareliya  thanks! i even tried that. its working with container thing. but not with tag thing
i did this
```
app:tag_border_color="@color/white"
app:tag_background_color="@color/white"
```

**Comment by ndeokar** [comment]
after going through detailed documentation of Attributes found that 

`app:tag_theme="none"`

this does the work! and it wasn't issue!
