### ISSUE TITLE
I used this  view,  I found  the attributes about tags are not wored;

### ISSUE THREAD

**Issue by feaverfei** [whilu/AndroidTagView#18]
way one:
        app:tag_text_color="@color/primary_blue"
        app:tag_border_color="@color/primary_blue"
        app:tag_background_color="@color/list_bg"
        way two:
        serchFgTagView.setTagBorderColor(getResources().getColor(R.color.primary_blue));
        serchFgTagView.setTagBackgroundColor(getResources().getColor(R.color.primary_blue));
        serchFgTagView.setTagTextColor(getResources().getColor(R.color.primary_blue));
These things that  i  used is not work,  why?

**Comment by whilu** [comment]
Look at this description: Set the theme. If you want to customize theme, remember set theme with ColorFactory.NONE first, then set other attributes. The same issue: [https://github.com/whilu/AndroidTagView/issues/13](https://github.com/whilu/AndroidTagView/issues/13). Thanks!

**Comment by feaverfei** [comment]
Thanks , so fast ! I'll try
