### ISSUE TITLE
能否添加个居中开关？

### ISSUE THREAD

**Issue by noblesky** [whilu/AndroidTagView#2]
假设一行 TAG 只有三个没有超过屏幕宽。能否添加个开关让开关居中？

**Comment by whilu** [comment]
@noblesky 你好。有时间我再把它加进去，如果可以你也可以自己添加和PR！

**Comment by whilu** [comment]
@noblesky 你好，现在已经支持居中了，```container_gravity```属性有```left```、```center```和```right```供使用，详见[README.md](https://github.com/whilu/AndroidTagView/blob/master/README.md)，最新库还未上传，现在你可以本地导入使用。非常感谢！！！
