### ISSUE TITLE
setDragState()调用有问题，导致不能响应long click

### ISSUE THREAD

**Issue by dengit** [whilu/AndroidTagView#3]
Revision Number @be87be7
bug描述：
- 当`TagContainerLayout`同时设置为可拖动，可点击，长按后，在不先拖动`子View`的前期下，长按`子View`，`子View`并不能响应`long click`，
- 只要一拖动任意`子View`后，即可正常响应长按

bug分析：
- 初始化`TagContainerLayout`时调用了`setDragState()`
- 在`setDragState()`中，当`mDragEnable`设置为`true`时（即可拖动），`mTagViewState`被设置为- `ViewDragHelper.STATE_DRAGGING`
- 但在处理`long click`的`runnable`中，`mTagViewState`需要等于`STATE_IDLE`才能触发长按处理。所以在在不先拖动`子View`的前期下`long click`无响应
- 拖动之后，`mTagViewState`会被`DragHelperCallBack.onViewDragStateChanged()`正常设置状态，所以才可响应`long click`

bug修复建议：
- `setDragState()`是否可删除？或者只是起到重置`mTagViewState=ViewDragHelper.STATE_IDLE`作用，这样可修复

- 根据`setDragState()`目前两处被调用的上下文分析得出：
 - `TagContainerLayout`初始化时 ：不调用`setDragState()`，按`mTagViewState`的初始值`ViewDragHelper.STATE_IDLE`
 - `setDragEnable()`中：不调用`setDragState()`，`mTagViewState`的值完全由`DragHelperCallBack.onViewDragStateChanged()`控制，这样比较清晰

**Comment by whilu** [comment]
@dengit 是的，那个方法没有啥用，是之前修点击事件和滑动冲突时遗留的，```mTagViewState```应该由```DragHelperCallBack.onViewDragStateChanged()```控制。已经把这个方法删除了。。分析的很棒！非常感谢！
