### ISSUE TITLE
Ripple Effect

### ISSUE THREAD

**Issue by yasaman93** [whilu/AndroidTagView#30]
I want ripple effect on each tag when user click on it. How can I do that?

**Comment by whilu** [comment]
Try like this, [Set ripple effect in layout file](https://github.com/whilu/AndroidTagView/blob/master/sample/src/main/res/layout/content_main.xml#L114-L116). 
This feature has supported in version 1.0.4. 😄

**Comment by yasaman93** [comment]
Thank you very very much :)
