### ISSUE TITLE
Default px dimensions of some attributes look weird on xxhdpi screens

### ISSUE THREAD

**Issue by hartmannj** [whilu/AndroidTagView#37]
I would recommend using dp for the default values of tag_horizontal_padding, tag_vertical_padding and tag_bd_distance.

**Comment by whilu** [comment]
Yes, I also considered this, I will revise this issue in the next version.
Thank u!😀

2016年12月19日 11:12，"hartmannj" <notifications@github.com>写道：

**Comment by whilu** [comment]
This feature has been updated in the latest version, so I close this issue 😁
