### ISSUE TITLE
Different colors for different tags

### ISSUE THREAD

**Issue by anantshah93** [whilu/AndroidTagView#41]
Does this support different colors for different tags?

I could not find it, so made some adjustments which allows you to pass a color array with the tags array, and sets different colors for different tags.

Do you accept pull requests? I can pass on the code?
![screenshot](https://cloud.githubusercontent.com/assets/13238619/22978057/251cc538-f3b7-11e6-9e54-ef3364c9606e.png)

**Comment by whilu** [comment]
It's not support different colors for different tags.

If you can make a PR for this feature, that's great!😄

2017-02-15 22:14 GMT+08:00 Anant Shah <notifications@github.com>:

**Comment by anantshah93** [comment]
I added this feature! [8480369] commit.(https://github.com/whilu/AndroidTagView/commit/8480369a7d863168a112741aebd6a637ff7b271c)
