### ISSUE TITLE
1.1.0版本Support包版本过高导致FloatingActionButton崩溃

### ISSUE THREAD

**Issue by a512509050** [whilu/AndroidTagView#48]
我们的项目使用的是23.4.0的版本，升级到1.1.0后报错，需要升级Support包。
可不可以兼容一下版本

**Comment by whilu** [comment]
@a512509050 
感谢！
我觉得你可以升级一下 Support 库的版本（保持最新的稳定版是最好的），我刚刚测试了```-v7:24.2.0```是可以正常使用的。

还有任何问题或意见一起可以讨论😄
