### ISSUE TITLE
Cross button should listen for on release instead of on press/hover

### ISSUE THREAD

**Issue by dcgavril** [whilu/AndroidTagView#49]
Hello and thank you for your great work.

I have seen that the cross button (remove tag) is listening for on press instead of on release and I believe that it could create issues for users like for example, if the user is trying to hover over the view to be able to scroll and there is no dialog to confirm the removal (yes/no) attached to the cross button, the tag will get removed instantly.

Thanks.

**Comment by whilu** [comment]
@dcgavril 
That's a very good suggestion! Thanks! I will improve this in next version!😄

**Comment by whilu** [comment]
This feature has been added in v1.1.1, so I close this issue. Thanks!
