### ISSUE TITLE
Get array list from tags

### ISSUE THREAD

**Issue by BenCherif** [whilu/AndroidTagView#5]
Hi sir, how i can retrieve array list (string ) from tags??

**Comment by whilu** [comment]
I'm sorry so late reply, there is no way to retrieve array list (string )
from tags, but you can get one tag text with 'getTagText(int position)'
method. If you need, I can add a method for get array list from tags in
next version. But I was busy these days, if you are anxious to use, you may
add the method according the source code, and you can make a PR for the new
code. Thanks!

2016-01-23 1:18 GMT+08:00 BenCherif <notifications@github.com>:

**Comment by BenCherif** [comment]
Hi sir ,thanks for your reply,when you will add the method ,i can wait a week or maybe two

**Comment by whilu** [comment]
Ok, no problem. I will add this functionality before Chinese New Year, just
within this weeks!

2016-01-23 21:59 GMT+08:00 BenCherif <notifications@github.com>:

**Comment by whilu** [comment]
@BenCherif Hello, I have added ```getTags()``` method for retrieve a list (string) from tags, more detail please refer ```README.md``` file. Thank u for your suggestion!

**Comment by BenCherif** [comment]
Thanks  sir , and you are wlce

**Comment by BenCherif** [comment]
getTags() doesn't exist sir !!

**Comment by whilu** [comment]
@BenCherif Sorry, the library has not uploaded to jCenter, you can use it locally, after fixed several bugs I will upload the library as soon as possible

**Comment by BenCherif** [comment]
ok sir i can waiting :)

**Comment by BenCherif** [comment]
Hi sir ,i need getTags() method if you can add it plse add it ASAP

**Comment by whilu** [comment]
@BenCherif Hi, If you are anxious to use ```getTags()``` method, you can get it with JitPack. Just write the following code, 
```
allprojects {
	repositories {
		maven { url "https://www.jitpack.io" }
	}
}
```
```
dependencies {
        compile 'com.github.whilu:AndroidTagView:1e5cfb6715'
}
```
it will help you get the code with ```getTags()``` method. And later when the new version is released, you just need replace the dependence with ```co.lujun:androidtagview:newversion```, this doesn't affect your use. Thanks!

**Comment by BenCherif** [comment]
ok thanks sir :)
