### ISSUE TITLE
Cross Size problem

### ISSUE THREAD

**Issue by hoseinit** [whilu/AndroidTagView#71]
Hello there,
Thanks for developing such a great library,
I have a problem when the Cross on a Tagview is Enabled, the Text of that Tag extends the size of the Tag and some Characters of it won't be shown. So I can't set a padding on the Tagview so that with Cross enabled All the Text could be shown.
What Should I do ?

**Comment by whilu** [comment]
Hello hoseinit,

Maybe there are some questions for you. If you set the attribute `tag_enable_cross ` as `true`, the cross will be enable. If the text inside the TagView are too long the text will be cut off and display ellipsis. If you want to set the padding for the cross, you should use `tag_cross_area_padding`, maybe this attribute will help you, or `tag_horizontal_padding` is for TagView's horizontal padding. 

If you also have problems, you can give me more describe about the issue, thanks😄

**Comment by hoseinit** [comment]
Thanks buddy,
`tag_horizontal_padding` did the trick, I was looking for extra space so that my text wouldn't exceed the space of tag.
Many thanks
