### ISSUE TITLE
TAG在垂直方向没有居中

### ISSUE THREAD

**Issue by brandlee** [whilu/AndroidTagView#72]
麻烦请教一下，从sample来看，所有的tag中文汉字没有垂直居中，请问有什么解决方法？

**Comment by whilu** [comment]
你好，
      不好意思，回复晚了。你可以看看 tag_bd_distance 这个属性，或许对你有帮助。


tag_bd_distance dimension The distance between baseline and descent(default
2.75dp)



2018-03-06 14:28 GMT+08:00 brandlee <notifications@github.com>:

**Comment by brandlee** [comment]
多谢，我最后就是用这个实现的，我觉得不居中的问题可以后续跟进一下，中文在view的绘制确实会存在不居中的问题，我看代码中确实也有处理的哈
