### ISSUE TITLE
Tag's top padding is different to bottom padding.

### ISSUE THREAD

**Issue by GiwonJang** [whilu/AndroidTagView#8]
Tag's top padding is different to bottom padding.
Bottom padding is less than top.

Sincerely.

**Comment by whilu** [comment]
Which padding do you mean, TagContainerLayout's padding or TagView's padding?

**Comment by GiwonJang** [comment]
I mean this.
![whilu androidtagview a tagview library for android customize your own drag effect 2016-02-05 10-32-49](https://cloud.githubusercontent.com/assets/3067050/12835650/6f01062c-cbf5-11e5-8616-6f52b2d8d1b4.png)

**Comment by whilu** [comment]
You can look at this mail,  similar problems with your, thanks!

......I added 'tag_bd_distance' attribute 4 adjust the distance
between baseline
and descent(I use your typeface test, when set 4.6dp, it will be center
vertical), i think that's will help u! Thanks!
[image: 内嵌图片 2]

2016-02-05 9:45 GMT+08:00 Giwon Jang <notifications@github.com>:

**Comment by GiwonJang** [comment]
Oh! Thanks @whilu 

Sincerely.
