### ISSUE TITLE
Gradle Error: Error:Cannot create variant 'android-lint' after configuration ':androidtagview:debugRuntimeElements' has been resolved

### ISSUE THREAD

**Issue by Nik2505** [whilu/AndroidTagView#81]
Hallo
i have android studio 3.0.1 with **classpath 'com.android.tools.build:gradle:3.1.3** and **distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip** and am trying to run the code but i am getting this error:
Cannot create variant 'android-lint' after configuration ':flexible-adapter:debugRuntimeElements' has been resolved.

any idea, how to solve it?

If I am trying to run with **classpath 'com.android.tools.build:gradle:3.0.1'** and **distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip** then It is working fine.

**Comment by anhtuan23** [comment]
Just comment out the `https://raw.githubusercontent.com/whilu/AndroidPublishLibrary ... ` line in the library module `build.gradle` file.
This bug has something to do with making Javadoc in newer Gradle version as seen here in [another project's issue.](https://github.com/davideas/FlexibleAdapter/issues/579)

**Comment by Nik2505** [comment]
@anhtuan23 tried with your solution but getting same error

**Comment by anhtuan23** [comment]
@Nik2505 Strange. I had that error awhile ago the resolved it that way. Why don't you try and clone my forked version. I am running it on the newest Gradle version. You can find it in this [link](https://github.com/anhtuan23/AndroidTagView). Use branch `Make-TagView-selectable`.

**Comment by Nik2505** [comment]
> Just comment out the apply from: 'https://raw.githubusercontent.com/whilu/AndroidPublishLibrary ...
I tried with second time and it's working now. Thanks for response.
