### ISSUE TITLE
在listview 中，设置点击事件无响应且不会调用setOnTagClickListener方法。

### ISSUE THREAD

**Issue by Jacky-Xu** [whilu/AndroidTagView#9]
使用场景：在listview的每个item里显示tagview，可以正常显示。点击tagview时不会调用setOnTagClickListener这个方法。请问怎么解决。

**Comment by whilu** [comment]
你好，不好意思，回复晚了。我会尽快查看bug修复，谢谢！

Jacky Xu <notifications@github.com>于2016年2月3日 周三15:53写道：

**Comment by whilu** [comment]
@Jacky-Xu 你好， 我测试了listview的使用场景，设置监听后是可以回调的。不知道是不是你代码里面哪里错了。你可以看看sample里的代码再试一下，有任何问题你可以在联系我。

**Comment by Jacky-Xu** [comment]
private void showLinearProject(){
        linearFlow.removeAllViews();

        for (int i = 0;i<1;i++){
            tagName.clear();
            LinearLayout major = (LinearLayout) LayoutInflater.from(getActivity()).inflate(R.layout.layout_item_major, null);
            TagContainerLayout tagContainerLayout = (TagContainerLayout) major.findViewById(R.id.tagview);
            TextView tag = (TextView) major.findViewById(R.id.tv_item_majorname);
            TextView icon = (TextView) major.findViewById(R.id.tv_item_icon);
            tag.setText(labelAndMajors.get(i).getLabelName());
            icon.setText(labelAndMajors.get(i).getLabelName().substring(0,1));
            List<CourseModel.DataEntity.LabelAndMajorsEntity.ProjectMajorsEntity> projectMajors=labelAndMajors.get(i).getProjectMajors();
            for(CourseModel.DataEntity.LabelAndMajorsEntity.ProjectMajorsEntity subname:projectMajors){
                tagName.add(subname.getSubjectName());
            }
            tagContainerLayout.setTags(tagName);
            tagContainerLayout.setTagTextSize(10);

            tagContainerLayout.setOnTagClickListener(new TagView.OnTagClickListener() {
                @Override
                public void onTagClick(int position, String text) {
                    AppUtils.showToast("pos" + position + text);
                    LoggerUtils.logE("11111", "pos" + position + text);
                }

                @Override
                public void onTagLongClick(int position, String text) {
                    AppUtils.showToast("pos" + position + text);
                }
            });
            linearFlow.addView(major);
        }
    } 

我把我的代码贴出来，你帮我看看是哪里的问题，setOnTagClickListener这个方法进不去。

**Comment by whilu** [comment]
@Jacky-Xu 你好，代码其实很简单，不过有个```tag_clickable```属性默认是```false```，要设置为```true```才能有效的，不知道你这个设置没有。```setIsTagViewClickable(boolean clickable)```方法也可以设置。

**Comment by aserour** [comment]
I faced the same problem, the way I found to resolve it is to call setOnTagClickListener before setTags

我面临同样的问题，我发现要解决它setTags前致电setOniTemClickListener方式

**Comment by Jacky-Xu** [comment]
@whilu  你好，我在布局xml文件设置了tag_clickable="true"的，我才发现onclick不了。

**Comment by Jacky-Xu** [comment]
@aserour  thanks, I solved the problem, thank you very much for your answer.

**Comment by Jacky-Xu** [comment]
@whilu  已经解决了这个问题了。@aserour给出了解决方法，要在setTags之前调用setOnTagClickListener才有效。

**Comment by whilu** [comment]
Good, thanks!!!

**Comment by whilu** [comment]
@Jacky-Xu @aserour thanks! the latest code have fixed this problem.

**Comment by ZengTianShengZ** [comment]
你好，我也碰到了同样的问题，我是用recycleView  的 , 根据上面提到的解决方法还是不行，
`tag_clickable="true"`
`setTags前致电setOniTemClickListener方式`
俩种方式都没能解决，请问还有其他原因吗，跟 recycleview有关吗

**Comment by suojiang** [comment]
@ZengTianShengZ 我也遇到了相同的问题，其他机型上 setTags之前（或者之后）设置setOnItemClickListener方式 都没问题，刚刚在三星note4 Android 6.0.1机子上测试点击偶尔可以，差不多30%几率可以调用OnClick 事件
