### ISSUE TITLE
Illegal color list!

### ISSUE THREAD

**Issue by Cutta** [whilu/AndroidTagView#97]
When you use setTags method with the color list like README.md it throws exception.
On version 1.1.7 setTags method's color list size should be 4, not 3. README.md should update like this:

List<int[]> colors = new ArrayList<int[]>();
//int[] color = {TagBackgroundColor, TabBorderColor, TagTextColor, TagSelectedBackgroundColor}
int[] color1 = {Color.RED, Color.BLACK, Color.WHITE, Color.CYAN};
int[] color2 = {Color.BLUE, Color.BLACK, Color.WHITE, Color.CYAN};
colors.add(color1);
colors.add(color2);
mTagcontainerLayout.setTags(tags, colors);

**Comment by whilu** [comment]
Thanks, I will update README.md soon. 😄

Cüneyt Çarıkçi <notifications@github.com> 于2019年3月15日周五 下午9:16写道：
