### ISSUE TITLE
非Android x版本

### ISSUE THREAD

**Issue by zhangle1** [whilu/AndroidTagView#98]
问下非最新Android版本应该怎么样导入

**Comment by whilu** [comment]
implementation 'co.lujun:androidtagview:1.1.5' // Try this version


zhangle1 <notifications@github.com> 于2019年3月18日周一 下午2:13写道：

**Comment by andyunoone** [comment]
With Android P and version 'co.lujun: androidtagview: 1.1.5' from the following error: java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

With Android P and version 'co.lujun: androidtagview: 1.1.7' from the following error: 
Unable to start activity ComponentInfo{unoone.aallianceassicurazioni/unoone.aallianceassicurazioni.NewsActivity}: android.view.InflateException: Binary XML file line #30: Binary XML file line #30: Error inflating class co.lujun.androidtagview.TagContainerLayout

Can you help me solve it? Thank you

**Comment by zhangle1** [comment]
谢谢 ，以解决 库很棒 ！
